using MauiApp1.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MauiApp1.Services;

public class PdfExportService
{
    public byte[] CreateJournalPdf(List<JournalEntry> entries, DateTime from, DateTime to)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Text($"Soft Space Journal Export ({from:MMM dd, yyyy} - {to:MMM dd, yyyy})")
                    .SemiBold().FontSize(16);

                page.Content().Column(col =>
                {
                    if (!entries.Any())
                    {
                        col.Item().Text("No entries found in this date range.").Italic();
                        return;
                    }

                    foreach (var e in entries)
                    {
                        col.Item().PaddingBottom(12).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);

                        col.Item().Text($"{DateTime.Parse(e.EntryDateKey):dddd, MMM dd, yyyy}  |  Mood: {e.PrimaryMood}")
                            .SemiBold();

                        if (!string.IsNullOrWhiteSpace(e.Title))
                            col.Item().Text($"Title: {e.Title}").FontColor(Colors.Grey.Darken2);

                        // ContentHtml is HTML; quick export: strip basic tags
                        var plain = StripHtml(e.ContentHtml ?? "");
                        col.Item().Text(plain);
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Soft Space");
                });
            });
        });

        return doc.GeneratePdf();
    }

    private static string StripHtml(string html)
    {
        // simple stripping (good enough for export)
        return System.Text.RegularExpressions.Regex.Replace(html, "<.*?>", string.Empty)
            .Replace("&nbsp;", " ")
            .Trim();
    }
}
