using MauiApp1.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Text.RegularExpressions;

namespace MauiApp1.Services;

public class PdfExportService
{
    public PdfExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] CreateJournalPdf(
        List<JournalEntry> entries,
        string fromDate,
        string toDate)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(12));

                // HEADER
                page.Header()
                    .Text($"Soft Space Journal Export ({fromDate} - {toDate})")
                    .SemiBold()
                    .FontSize(16);

                // CONTENT
                page.Content().Column(column =>
                {
                    if (entries.Count == 0)
                    {
                        column.Item().Text("No entries found.");
                        return;
                    }

                    foreach (var entry in entries)
                    {
                        // ⚠ Convert EVERYTHING to string
                        string date = entry.EntryDateKey ?? "";
                        string mood = entry.PrimaryMood ?? "";
                        string title = entry.Title ?? "";
                        string content = StripHtml(entry.ContentHtml ?? "");

                        column.Item()
                              .PaddingBottom(12)
                              .BorderBottom(1)
                              .BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2);

                        column.Item()
                              .Text($"{date} | Mood: {mood}")
                              .SemiBold();

                        if (!string.IsNullOrWhiteSpace(title))
                        {
                            column.Item().Text($"Title: {title}");
                        }

                        column.Item().Text(content);
                    }
                });

                // FOOTER
                page.Footer()
                    .AlignCenter()
                    .Text("Generated by Soft Space");
            });
        });

        return document.GeneratePdf();
    }

    private static string StripHtml(string html)
    {
        return Regex
            .Replace(html, "<.*?>", string.Empty)
            .Replace("&nbsp;", " ")
            .Trim();
    }
}
